object FrameBtnPadrao: TFrameBtnPadrao
  Left = 0
  Top = 0
  Width = 331
  Height = 64
  TabOrder = 0
  object pnlAtualizar: TPanel
    Left = 17
    Top = 11
    Width = 89
    Height = 41
    Caption = 'Atualizar'
    Color = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    OnMouseEnter = pnlAtualizarMouseEnter
    OnMouseLeave = pnlAtualizarMouseLeave
  end
  object pnlEditar: TPanel
    Left = 121
    Top = 11
    Width = 89
    Height = 41
    Caption = 'Editar'
    Color = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 1
    OnMouseEnter = pnlAtualizarMouseEnter
    OnMouseLeave = pnlAtualizarMouseLeave
  end
  object pnlSair: TPanel
    Left = 226
    Top = 11
    Width = 89
    Height = 41
    Caption = 'Sair'
    Color = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 2
    OnMouseEnter = pnlAtualizarMouseEnter
    OnMouseLeave = pnlAtualizarMouseLeave
  end
end
